### ISSUE TITLE
Don't figure out how to use it

### ISSUE THREAD

**Issue by feolea** [devopsfaith/krakend-lua#1]
Hey guys, 

I think I'm missing something dumb basic knowledge to install this interpreter on my docker image, tried to follow the [docs](https://www.krakend.io/docs/endpoints/lua/), but some points are a little confusing to me, so if anyone can help with a basic example of a working stack would be really appreciated!

- .lua file sample
- What is that "pre" and "post" config for? Is it just to declare pre: pre, post: post at config and nothing more?
- a sample krakend.json with this config, I tried putting the config at the endpoint level, but when krakend starts it just print: `DEBUG: lua: no extra config` and anything that I put at lua file makes no difference at all, the endpoint works default without any change..

May I have to compile something to install the extension? I am just putting the extra config like that:
```
"endpoints": [
    {
      "endpoint": "/pages",
      "method": "POST",
      "extra_config": {
        "github.com/devopsfaith/krakend-lua": {
          "sources": ["bla.lua"],
          "pre": "pre",
          "post": "post",
          "live": true,
          "skip_next": true
        }
      },
```

About the filename at the sources config, I tried with full path too, but I don't know if the file was loaded or not, there is no log about it, tried with md5 too without success, gave execution permission to file, chown the file to kong user...

The documentation says something about proxy type, but I don't have any idea where I could configure that type..

I'm using the image devopsfaith/krakend:latest to build my container reading the config from /etc/krakend volume.

**Comment by john5000** [comment]
hey @feolea,

I tried out the lua scripting and have an example that works that may help.   

The namespace used in the documentation page is wrong and so once that is fixed you can make much better progress.  (I've submitted a PR for the doc page that fixes and clarified several points).  

Here is an example that will work.

    "endpoints": [
        {
            "endpoint": "/pages",
            "method": "POST",
            "extra_config": {
                "github.com/devopsfaith/krakend-lua/proxy": {
                "pre": "print('Lua proxy!'); local r = request.load(); r:header('X-from-lua', '1234');",
            }
        }


The `DEBUG: lua: no extra config` normally shows up three times in the log (once for each point that lua can be configured).  When you add the above, one of them should go away -- so from there you can tell the logic is recognized.  Then when executed it will show "Lua proxy!" in the logs.  And the destination site will get an extra header "X-from-lau".

Note: I could not get the full functionality of lua to work in the fashion described in the documentation page.   The only part I got working is reading the body (but can't updated) and can read and set the header fields, but only going to the endpoints, not coming back in the response.

**Comment by kpacha** [comment]
check out the running examples included into the integration tests: https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/krakend.json#L483-L555

**Comment by john5000** [comment]
Awesome resource. Thanks for pointing that out.

**Comment by feolea** [comment]
Thankyou all guys, it will help a lot!
