### ISSUE TITLE
Adding an empty list/array to a response 

### ISSUE THREAD

**Issue by tobley** [devopsfaith/krakend-lua#14]
I am unable to add an empty list to be added to a response. I have tried something like this: 
```
          "extra_config": {
            "github.com/devopsfaith/krakend-lua/proxy/backend": {
              "post": "local r = response.load(); local responseData = r:data(); responseData:set('newEmptyArrayItem', {?? what goes here ??});"
            }
          }
``` 

From what I can tell from my day of Lua learning is that tables and arrays share similar declarations for empty (e.g. local emptyTable = {} and local emptyArray = {}). 

So krankend-lua returns an empty object ({}) which is similar to the this shortcoming [here](https://stackoverflow.com/questions/60398791/lua-script-coverts-empty-array-to-object).

Maybe there could be a new helper for list new (static)?

**Comment by kpacha** [comment]
my interpretation of the documentation is that arrays are not a lua type.

> There are eight basic types in Lua: nil, boolean, number, string, userdata, function, thread, and table.

The internals of the table type allow you to also use the type for collections, but it's still a table.

> The table type implements associative arrays. An associative array is an array that can be indexed not only with numbers, but also with strings or any other value of the language, except nil.

Check out this test for more details on how to manipulate collections in a lua script and how they are returned from the lua vm: https://github.com/devopsfaith/krakend-lua/blob/master/proxy/proxy_test.go#L101

https://github.com/devopsfaith/krakend-lua/blob/master/proxy/proxy_test.go#L184-L190 generates the collection
https://github.com/devopsfaith/krakend-lua/blob/master/proxy/proxy_test.go#L259-L262 shows you how the collection will be returned to the user

cheers!

**Comment by tobley** [comment]
Thanks @kpacha. I'm able to manipulate the collections like the example you provided.

I was thinking that even though lua doesn't have an array type, the underlying userdata luaList would allow for a static helper method that worked something like this:

```
responseData:set('newEmptyArrayItem', list.new({})
responseData:set('newStringList', list.new({'a','b','c'})
```
which would give a response 
```
{
  "newEmptyArrayItem": [],
  "newStringList": ["a","b","c"],
  ...
}
```

I appreciate the help and think krakend is awesome after spending the last few days learning about it.
