### ISSUE TITLE
Change Host Url whit LUA

### ISSUE THREAD

**Issue by Castronebe** [devopsfaith/krakend-lua#19]
hi, 

I'm trying to change the host url depending on a request param, but from "github.com/devopsfaith/krakend-lua/proxy/backend" I can't access this parameter 

example: 

`{
  "endpoint": "/example/availability/{country}/info/{storeId}",
  "method": "GET",
  "output_encoding": "no-op",
  "timeout": "900ms",
  "headers_to_pass": [
    "*"
  ],
  "querystring_params": [
    "*"
  ],
  "cache_ttl": "0s",
  "extra_config": {
    "github.com/devopsfaith/krakend-lua/router": {
      "pre": "local req = ctx.load(); print(\"contx params: \"..req:params('country')); "
    }
  },
  "backend": [
    {
      "url_pattern": "/api/availability/{storeId}/exx",
      "timeout": "1000ms",
      "encoding": "no-op",
      "sd": "static",
      "host": [
        "example.com"
      ],
      "disable_host_sanitize": "false",
      "extra_config": {
        "github.com/devopsfaith/krakend/http": {
          "return_error_details": "backend_partners-push"
        },
        "github.com/devopsfaith/krakend-lua/proxy/backend": {
          "pre": "local r = request.load();  if('CL'== r:params('country')) then r:url(\"https://example.cl\"..r:path()) end",
          "live": true,
          "allow_open_libs": true
        }
      }
    }
  ]
}`

I can access parameter in  "github.com/devopsfaith/krakend-lua/router" but in "github.com/devopsfaith/krakend-lua/proxy/backend" not. 

you know how i can do it?

Thanks!

**Comment by kpacha** [comment]
there is an issue with your lua snippet. Here you have a fixed version:

```
"github.com/devopsfaith/krakend-lua/proxy/backend": {
    "pre": "local r = request.load(); if string.match('CL', r:params('Country')) then r:url(\"https://example.cl\"..r:path()) end;",
    "allow_open_libs": true
}
```

cheers!
