### ISSUE TITLE
Passing claims array to query params

### ISSUE THREAD

**Issue by dalmenar** [devopsfaith/krakend-lua#20]
hi , i'm trying to get a claim from token with these lua script files  [link](https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/lua/collection.lua#L1-L10)

I have a token decoded, but i don't know why, the payload part is not decoded (alg RS256):
`
{"alg":"RS256","typ":"JWT","kid":"xxxxxxxxxxxxxxxxxx"}☺��Ո��Ս��љ����Ռᑈ先��ɍ����͍�����l�ɕ�������ɥє���ɕ������ɕ�������ɵձ�̈��ɕ������͕������͕�̉t��ѕ���Ј艕��}ѕ�����Ĉ����Ј����������ܰ�����������������☺�3_-☻♀���♂3��PQ;▬�Q7MH]�(db�B�(k♀�☼�#������R�ٺ►�� �♀☼hza↨���8�v֋�5�X)�YG↨�B�x�҇1lʬ¼�؋!iP��8��E��4�H���JK�N�♣}� krakend_ce_1 | tAJ�H��0�xQ����� krakend_ce_1 | IYl6}→�K2�eN%M�M��նc&3U�A�~�☼�∟'If↔4�z krakend_ce_1 | K�&�=�,�)]Ba�A���͒ͯ>♦� E�Q�☻���♀��yi☻9�7▲��׀�☼m�{d��i��԰�;3�Q♀˥!m�=UoFxi�Zk:�=��3Δ�g☺.�w��B��\→q�&☺� ♂ �@♣Ъ�p�wk♀‼���m�:��{�+JQ�J�|=}ggVӅ��→P♣k��M�&�B�Q�('�_"#���R��֩�9�����9u,w�♦�r4܄���'7d%☻☺�,�*ԙS��!*��.�♀�→hG�&Ð�W$▬@↕5♣�@��CǋL�[�չT☺c��Y'1�됑\6�A���C"�e��n޷b���,Ҋ�}����*Y��T`

I can access only to header fields. I've used method from_base64 from this: https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/lua/base64.lua

any idea?

Thanks!

**Comment by kpacha** [comment]
can you share your actual lua snippet?

**Comment by dalmenar** [comment]
Sure! I need the first part because i have 3 different cookies. But the variable token is valid. (i have checked in jwt.io). 
xxxxx is the name of the cookie i need.

`
    print('Lua proxy!')
    local r = request.load()
    local cookies=r:headers('Cookie')
    local token
    
    for cookie in string.gmatch(cookies, "[^%s]+") do
    
        local exist=string.find(cookie,'xxxxxx')
    
        if exist ~= nil and exist ~= '' then
            
        local lenCookieName = string.len('xxxxxx')
        local last = string.len(cookie)
        token = string.sub(cookie, lenCookieName+2, last-1)
        print(token)
        end
        
    end
    
    print('Token')
    print(token)
    
    local decoded = from_base64(token)
    print('Decoded')
    print(decoded)

    local jwtData = json_parse(decoded)
    print('jwtData')
    print(jwtData)

    print('tenant')
        
    for i, v in pairs(jwtData) do --loop through the table-- 
        print(i) --print the number--
        print(v) --print the value--
    end
`


Result:

`
krakend_ce_1     | Lua proxy!
krakend_ce_1     | eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjYwN2VkNWI2Zjc2ZjI2ODQ5NmFhMzk4OCJ9.eyJzdWIiOiI1Y2U2NGZmZDhkOTVjOGRiOWFiMzAyY2YiLCJzY29wZSI6WyJyZWNpcGVzOndyaXRlIiwicmVjaXBlczpyZWFkIiwiZm9ybXVsYXMiLCJyZWNpcGVzOnNlbmQiLCJ1c2VycyJdLCJ0ZW5hbnQiOiJlY29fdGVuYW50MDEiLCJpYXQiOjE2MjE1MTA3MTcsImV4cCI6MTYyMTU5NzExN30.eczXy0_DOHyzgsz3tpQUTsWqlE3TUhd9ChkYslCqyhrDMwP3COdltLGyftSpNm6EM3Z_nhNmt-DvbloMMKuL1LOQA3JD-9oemEXjvqMOJN2ANaLzzXTWCmIYwhZ-EcX5UI-nXji0ocxbMqswrwA5tiLIWlQivQ4tMpFh5c0mUj457H3SkucTuKfBX22CnRBSpcASPTGMOd4UdcH8KztpfEKSVlsNn0al0syoGVOJU3KTc3c1bZjJjNVp0GZfsYP0xwnSWYdNIJ6CkuHJpQ96Cz7KV1CYapBmRvvw8LNks2vPgSmCUXshlGpAo2a7-yFzXlpAjnSNx6gtNe-ww9t7ntki8kbcWmdndSwrzsz5VEMy6UhbfOcPVVvRgd4aYtaazruqD3q-OwzzpTpZwEu0ne0s0KW01wacb8m-YEJQQv7QAXQqolw43drDBP9nbltuTqUvnvHK0pRQ-izSsV8PX1nZ1bThcU-5hpQBWu9202DJtx_gFHQKCfkXyIjm42AUpvU1qnstDn1YJg-uOfVOXUsd8oE9XI03ISliaknN2Ql-gGHLPAq1JlTv5chKoLHLuEMqBpoR44mwRvvw8LNks2vPgSmCUXshlGpAo2a7-yFzXlpAjnSNx6gtNe-ww9t7ntki8kbcWmdndSwrzsz5VEMy6UhbfOcPVVvRgd4aYtaazruqD3q-OwzzpTpZwEu0ne0s0KW01wacb8m-YEJQQv7QAXQqolw43drDBRvvw8LNks2vPgSmCUXshlGpAo2a7-yFzXlpAjnSNx6gtNe-ww9t7ntki8kbcWmdndSwrzsz5VEMy6UhbfOcPVVvRgd4aYtaazruqD3q-OwzzpTpZwEu0ne0s0KW01wacb8m-YEJQQv7QAXQqolw43drDBP9nbltuTqUvnvHK0pRQ-izSsV8PX1nZ1bThcU-5hpQBWu9202DJtx_gFHQKCfkXyIjm42AUpvU1qnstDn1YJg-uOfVOXUsd8oE9XI03ISliaknN2Ql-gGHLPAq1JlTv5chKoLHLuEMqBpoR44mw5_aVP9nbltuTqUvnvHK0pRQ-izSsV8PX1nZ1bThcU-5hpQBWu9202DJtx_gFHQKCfkXyIjm42AUpvU1qnstDn1YJg-uOfVOXUsd8oE9XI03ISliaknN2Ql-gGHLPAq1JlTv5chKoLHLuEMqBpoR44mw5_aVyQWQBI1BbJ-59VDx4tMylur1blUAWOd41knMfDrkJFcNpFgGghBh7ShQyK6ZauWbt63Yvjgm_zSiqF9tJiyoipZtZ9U
krakend_ce_1     | Decoded                                                                                                                               ����͕�̉t��ѕ���Ј艕��}ѕ�����Ĉ����Ј����������ܰ�����������������☺�3_-☻♀���♂3��PQ;▬�Q7MH]�(db�B�(k♀�☼�#������R�ٺ►��
krakend_ce_1     | {"alg":"RS256","typ":"JWT","kid":"607ed5b6f76f268496aa3988"}☺��Ո��Ս��љ����Ռᑈ先��ɍ����͍�����l�ɕ�������ɥє���ɕ������ɕ�������ɵձ�̈��ɕ������
͕������͕�̉t��ѕ���Ј艕��}ѕ�����Ĉ����Ј����������ܰ�����������������☺�3_-☻♀���♂3��PQ;▬�Q7MH]�(db�B�(k♀�☼�#������R�ٺ►��
�♀☼hza↨���8�v֋�5�X)�YG↨�B�x�҇1lʬ¼�؋!iP��8��E��4�H���JK�N�♣}�
krakend_ce_1     | tAJ�H��0�xQ�����                                                                                                                                                                                                                                                                          ♂
krakend_ce_1     | IYl6}→�K2�eN%M�M��նc&3U�A�~�☼�∟'If↔4�z                                                                                                ��n޷b���,Ҋ�}����*Y��T
krakend_ce_1     | K�&�=�,�)]Ba�A���͒ͯ>♦�       E�Q�☻���♀��yi☻9�7▲��׀�☼m�{d��i��԰�;3�Q♀˥!m�=UoFxi�Zk:�=��3Δ�g☺.�w��B��\→q�&☺�
                                                                                                                                                      ♂�@♣Ъ�p�wk♀‼���m�:��{�+JQ�J�|=}ggVӅ��→P♣k��M�&�B�Q�('�_"#���R��֩�9�`����9u,w�♦�r4܄���'7d%☻☺�,�*ԙS��!*��.�♀�→hG�&Ð�W$▬@↕5♣�@��CǋL�[�չT☺c��Y'1�됑\6�`A���C"�e�
�n޷b���,Ҋ�}����*Y��T
krakend_ce_1     | jwtData
krakend_ce_1     | table: 0xc000e007e0
krakend_ce_1     | tenant
krakend_ce_1     | alg
krakend_ce_1     | RS256
krakend_ce_1     | typ
krakend_ce_1     | JWT
krakend_ce_1     | kid                                                                                                                                   fused
krakend_ce_1     | 607ed5b6f76f268496aa3988
`

**Comment by kpacha** [comment]
a JWT token is a concatenation of 3 base64-encoded json objects, joined by a dot `.`... you should split the token by `.` before decoding the token.

notice the linked code extracts just the body of the token (`string.sub(authHeader, first+1, last-1)`):
``` 
	local authHeader = req:headers("Authorization")
	local first = string.find(authHeader, "%.")
	local last = string.find(authHeader, "%.", first+1)
	local rawData = string.sub(authHeader, first+1, last-1)
	local decoded = from_base64(rawData)
	local jwtData = json_parse(decoded)
```

**Comment by alombarte** [comment]
I am closing this issue as it doesn't look anything related with the component but with the usage of Lua itself
