### ISSUE TITLE
Memory and file descriptors leak

### ISSUE THREAD

**Issue by Castronebe** [devopsfaith/krakend-lua#24]
I found that when I use the "http_response.new" function in LUA it works fine but it generates a memory and file descriptor leak

I use 1.2 version.

#Example:
function example_leak()
local bodyToSend = '{"store_ids":[119],"country":"CO"}'
local headers = {["email"] = "carlos.castro@yuyuy.com", ["Content-Type"] = "application/json"}
local r = http_response.new("http://mydomain.com/accounts/auth/stores/validate", "POST", bodyToSend, headers)
print("validate_partners_stores_user http status response: " .. r:statusCode())
end

**Comment by kpacha** [comment]
![gc_krakend_lua](https://user-images.githubusercontent.com/1307694/129411394-1e0be6b7-b966-4693-852f-68aa3355c190.png)

I'm not able to reproduce the memory leaks (I'm using your lua snippet). I can see how the stack gets bigger as the number of http requests increases and then I see how the GC performs as expected, but I don't see any memory leak.

The increase on the baseline memory consumption is due to the way the go apps and the SO deal with free memory, but so far I can't reproduce the memory leak scenario.

**Comment by Castronebe** [comment]
Is it possible that it is a problem of the krakend version we use (1.2)?

**Comment by Castronebe** [comment]
I tried the latest version of Krakend (1.4.1) and the problem persists. 
The problem is because it does not set free the tcp port and the file descriptors are taken forever. 
I do the test with jmeter, I make a 2k request and the problem is evident.
[krakend.zip](https://github.com/devopsfaith/krakend-lua/files/7010470/krakend.zip)
![image](https://user-images.githubusercontent.com/7536958/129978846-e5b09de6-7377-4a53-8883-1fd47e59c22c.png)

**Comment by Castronebe** [comment]
Hi @kpacha, news?

**Comment by kpacha** [comment]
hi, @Castronebe 
I wasn't able to reproduce any memory leak using the `http_response` helper. but I was able to reproduce scenarios where the system runs out of file descriptors due the way the lua middleware deals with responses.
I'm adding a `close` dynamic method to the `http_response` type, so user can free the resources as soon as they are not needed any more. the code, here: https://github.com/devopsfaith/krakend-lua/commit/728855f9797dcbdbdf1d047a302b4c80e0618f75

Using your own example with the new version:

```
function validate_partners_stores_user()
   local bodyToSend = '{"store_ids":[119],"country":"CO"}'
   local headers = {["email"] = "carlos.castro@rappi.com", ["Content-Type"] = "application/json"}
   local r = http_response.new("http://internal-microservices.dev.rappi.com/partners-indicators/statistics/rating/order_products/most_erroneous", "POST", bodyToSend, headers)
   print("validate_partners_stores_user http status response: " .. r:statusCode())
   r:close()
end
```

so the buffer for the response body is closed and the related resources free before exiting the execution of the lua snippet.

on the other hand, keep in mind that you can fine tune your configuration for the http transport layer, such as setting a value for `max_idle_connections_per_host` bigger than the default (2), as well as checking the ulimit defined for your OS

**Comment by Castronebe** [comment]
Perfect, thanks 
when does the new version come out?

**Comment by kpacha** [comment]
Q1 2022, we hope
